# testing all accounts retrieval
GET http://localhost:3000/api/account/get

###
# testing new account creation
POST http://localhost:3000/api/account/create
Content-Type: application/json

{
  "firstName": "v",
  "lastName": "2v1",
  "email": "vlvad",
  "password": "916v4771817"
}
###
# testing account deletion
GET http://localhost:3000/api/account/delete
Content-Type: application/json

{
  "email": "vlvad"
}

###
# testing account update
POST http://localhost:3000/api/account/update
Content-Type: application/json

{
  "_id": "65fa68ddb5af4c789af6acb7",
  "email": "vlvad",
  "firstName": "stat",
  "lastName": "2v1",
  "password": "771817",
  "type": "admin",
  "games": []
}
###
# testing account sign in
POST http://localhost:3000/api/account/signin
Content-Type: application/json

{
  "email": "vlvad",
  "password": "771817"
}

###
# testing game retrieval
GET http://localhost:3000/api/game/get

###
#GAMES
# testing new game creation
POST http://localhost:3000/api/game/create
Content-Type: application/json

{
  "name": "game3",
  "startDate": "2021-01-01",
  "endDate": "2021-01-01",
  "players": []
}

###
# testing game deletion
GET http://localhost:3000/api/game/delete
Content-Type: application/json

{
  "_id": "65fbae1a431cb7764f2035ff"
}

###
# testing game update
POST http://localhost:3000/api/game/update
Content-Type: application/json

{
  "_id": "65fbb60873430f4491d28705",
  "name": "game4",
  "startDate": "2021-01-01",
  "endDate": "2021-01-01",
  "players": []
}
